name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linter:
    name: Ruff Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
        if: false

  testexactmatch:
    name: Exact Match Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest
    - name: Run Test
      run: pytest pepmatch/tests/test_exact_match.py

  testmismatch:
    name: Mismatch Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest
    - name: Run Test
      run: pytest pepmatch/tests/test_mismatching.py

  testbestmatch:
    name: Best Match Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest
    - name: Run Test
      run: pytest pepmatch/tests/test_best_match.py

  testdiscontinuoussearch:
    name: Discontinuous Epitope Search Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest
    - name: Run Test
      run: pytest pepmatch/tests/test_discontinuous_search.py

  testparallelmatch:
    name: Parallel Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest
    - name: Run Test
      run: pytest pepmatch/tests/test_parallel_match.py